version: '3.8'
services:
  oxygen:
    image: ghcr.io/oxygenpay/oxygen:latest
    command: all-in-one --skip-config
    env_file: [ oxygen.env ]
    volumes: [ 'app-volume:/app' ]
    ports: [ '80:80' ]
    networks: [ net-oxygen ]
    depends_on: [ postgres ]
    restart: on-failure

  postgres:
    image: postgres:15-alpine
    restart: on-failure
    environment:
      # don't forget to change credentials!
      - POSTGRES_DB=oxygen
      - POSTGRES_USER=oxygen
      - POSTGRES_PASSWORD=Hasan@4455
    volumes:
      - 'pg-data:/var/lib/postgresql/data'
    ports: [ '5432:5432' ]
    networks: [ net-oxygen ]

networks:
  net-oxygen:

volumes:
  app-volume:
  pg-data:
